spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/restaurants/** , /api/v1/menu-items/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/** , /api/v1/auth/**
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/notifications/**
server:
   port: 9000
