management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
# Ensure Prometheus metrics export is enabled for micrometer
management.metrics.export.prometheus.enabled=true
