management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
# Ensure Prometheus metrics export is enabled for micrometer
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=https://cnpm-food-frontend-lr3u.onrender.com
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*