spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/v1/restaurants/**, /api/v1/menu-items/**
          filters:
            - name: CircuitBreaker
              args:
                name: restaurantCircuitBreaker
                fallbackUri: forward:/fallback/restaurant
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/user
                  
        # Swagger UI routes for each service
#        - id: user-service-swagger
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/swagger-ui/**, /user-service/api-docs/**
#          filters:
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#
#        - id: restaurant-service-swagger
#          uri: lb://RESTAURANT-SERVICE
#          predicates:
#            - Path=/restaurant-service/swagger-ui/**, /restaurant-service/api-docs/**
#          filters:
#            - RewritePath=/restaurant-service/(?<segment>.*), /$\{segment}
#
#        - id: order-service-swagger
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order-service/swagger-ui/**, /order-service/api-docs/**
#          filters:
#            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        timeoutDuration: 5s
        failureRateThreshold: 50
    instances:
      restaurantCircuitBreaker:
        aseConfig: default
      orderCircuitBreaker:
        aseConfig: default
      userCircuitBreaker:
        aseConfig: default

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
