[server]
protocol = http
http_port = 3000
; domain = localhost

[security]
; admin_user and admin_password can be set via env vars GF_SECURITY_ADMIN_USER / GF_SECURITY_ADMIN_PASSWORD
admin_user = admin

[users]
auto_assign_org = true

[auth]
# If Alloy requires license via env var GF_ENTERPRISE_LICENSE, set it in Windows system env

[log]
mode = console
