name: CI - API Gateway

# Chạy cho nhánh QUY-TRÌNH-1
on:
  push:
    branches:
      - QUY-TRÌNH-1
  pull_request:
    branches:
      - QUY-TRÌNH-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      # Nếu bạn cần MySQL hoặc Redis cho test, uncomment và chỉnh port
      # mysql:
      #   image: mysql:8
      #   env:
      #     MYSQL_ROOT_PASSWORD: root
      #     MYSQL_DATABASE: testdb
      #   ports:
      #     - 3306:3306
      #   options: >-
      #     --health-cmd "mysqladmin ping"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 3
    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3
      # Setup JDK 21 (tương thích Spring Boot 3.x)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      # Cache Maven dependencies để tăng tốc
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Build project
      - name: Build with Maven
        run: mvn clean install -DskipTests=false
      # Run tests
      - name: Run unit & integration tests
        run: mvn test
      # Optional: publish test results (JUnit)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
