name: Auto PR -> QUY-TRÌNH-1

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ src ]

jobs:
  detect-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            quy_trinh_1:
              - 'src/quy-trinh-1/**'
              - 'backend/service-a/**'
              - 'frontend/component-a/**'
            # nếu muốn trigger với mọi thay đổi trong src, uncomment:
            # quy_trinh_1:
            #   - 'src/**'

      - name: Debug outputs
        run: |
          echo "quy_trinh_1=${{ steps.changes.outputs.quy_trinh_1 }}"

      - name: Create PR -> QUY-TRÌNH-1
        if: steps.changes.outputs.quy_trinh_1 == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: QUY-TRÌNH-1
          branch: auto/src-to-quy-trinh-1-${{ github.sha }}
          title: 'Auto-sync: src -> QUY-TRÌNH-1'
          body: |
            Automatic PR from `src` branch to `QUY-TRÌNH-1`.
            Changed paths matched the QUY-TRÌNH-1 filter.
          commit-message: 'chore(ci): sync src -> QUY-TRÌNH-1'
          delete-branch: true