name: Auto PR -> QUY-TRÌNH-1

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ 'QUY-TRÌNH-1' ]

jobs:
  build-and-test:
    name: Build & Test (Maven + Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm exec -- ng build --configuration=production

      - name: Run frontend tests
        working-directory: frontend
        run: npm test --if-present

  create-pr-qt1-to-main:
    name: Create PR QUY-TRÌNH-1 -> main (if missing)
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show last commit
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          git --no-pager log -1 --pretty=oneline

      - name: Ensure PR QUY-TRÌNH-1 -> main exists
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const base = "main";
            const head = "QUY-TRÌNH-1";
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const { data: prs } = await github.rest.pulls.list({
              owner, repo, head: `${owner}:${head}`, base, state: "open"
            });

            if (prs.length > 0) {
              console.log(`PR already exists: ${prs[0].html_url}`);
            } else {
              const { data: pr } = await github.rest.pulls.create({
                owner, repo,
                title: `Auto PR: ${head} -> ${base}`,
                head,
                base,
                body: "Automatic PR created by workflow after push to QUY-TRÌNH-1"
              });
              console.log(`Created PR: ${pr.html_url}`);
            }