name: Auto PR -> QUY-TRÌNH-1

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: ['QUY-TRÌNH-1' ]

jobs:
  detect-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            quy_trinh_1:
              - 'src/quy-trinh-1/**'
              - 'backend/service-a/**'

      - name: Debug outputs
        run: |
          echo "quy_trinh_1=${{ steps.changes.outputs.quy_trinh_1 }}"

      - name: Create PR -> QUY-TRÌNH-1
        if: steps.changes.outputs.quy_trinh_1 == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: QUY-TRÌNH-1
          branch: auto/src-to-quy-trinh-1-${{ github.sha }}
          title: 'Auto-sync: src -> QUY-TRÌNH-1'
          body: |
            Automatic PR from `src` branch to `QUY-TRÌNH-1`.
            Changed paths matched the QUY-TRÌNH-1 filter.
          commit-message: 'chore(ci): sync src -> QUY-TRÌNH-1'
          delete-branch: true

  create-pr-qt1-to-main:
    name: Create PR from QUY-TRÌNH-1 -> main
    runs-on: ubuntu-latest
    # chỉ chạy khi event là push lên QUY-TRÌNH-1
    if: github.ref == 'refs/heads/QUY-TRÌNH-1'
    steps:
      - name: Checkout QUY-TRÌNH-1
        uses: actions/checkout@v4
        with:
          ref: QUY-TRÌNH-1
          fetch-depth: 0

      - name: Create PR from QUY-TRÌNH-1 to main
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: QUY-TRÌNH-1
          title: 'Auto PR: QUY-TRÌNH-1 -> main'
          body: |
            This PR was created automatically from branch `QUY-TRÌNH-1` after a push.
          draft: false
          delete-branch: false