name: Auto PR -> QUY-TRÌNH-1

on:
  push:
    branches:
      - src

jobs:
  create-pr-to-QUY-TRÌNH-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          # adjust filters to match which areas should trigger QUY-TRÌNH-1
          filters: |
            src:
              - 'src/**'
              - 'backend/**'
            frontend:
              - 'frontend/**'
            common:
              - 'pom.xml'
              - '.github/**'
      - name: Create pull request to QUY-TRÌNH-1
        if: steps.changes.outputs.src == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: QUY-TRÌNH-1
          branch: auto/src-to-QUY-TRÌNH-1-${{ github.sha }}
          title: 'Auto-sync: apply recent src changes -> QUY-TRÌNH-1'
          body: |
            This PR was created automatically from branch `src` by the CI workflow.
            Changed paths matched the QUY-TRÌNH-1 filter (src/** or backend/**).
            Please review and merge.
          commit-message: 'chore(ci): sync src -> QUY-TRÌNH-1'
          delete-branch: true