name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # hoặc QUY-TRÌNH-1 nếu bạn muốn deploy khi branch đó update

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend (Angular)
        working-directory: frontend
        run: npm run build -- --configuration=production --base-href "/CNPM-Food/"

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist/frontend/browser  # đường dẫn chứa file build ra (có thể là dist/app-name)

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4